name: Main workflow
on: [push]
jobs:
  Ubuntu:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
