name: ' GitHub Issue Due Dates Action'
description: 'Add overdue labels to past-due GitHub issues'
author: 'Alex Leventer'
inputs:
  GH_TOKEN:
    description: GitHub token used to make API requests
    required: true
branding:
  icon: 'calendar'
  color: 'purple'
runs:
  using: 'node12'
  main: 'dist/app.js'
