name: Main workflow
on: [push]
jobs:
  Ubuntu:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@1.0.4
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
